# Generated by Django 6.0.5 on 2026-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('ds', 'Data Science'), ('ai', 'Artificial Intelligence'), ('ec', 'Electronics & Communication'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ba', 'Business Administration'), ('bca', 'BCA'), ('mca', 'MCA')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
